package Http;

public enum EndPoint {
    GET_ALL_SIMPLE,
    GET_ALL_EPIC,
    GET_ALL_SUB,
    GET_SIMPLE_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUB_BY_ID,
    GET_ALL_TASKS,
    GET_ALL_EPIC_SUB,
    GET_HISTORY,
    POST_ADD_SIMPLE,
    POST_ADD_EPIC,
    POST_ADD_SUB,
    POST_UPDATE_SIMPLE,
    POST_UPDATE_EPIC,
    POST_UPDATE_SUB,
    DELETE_ALL_SIMPLE,
    DELETE_ALL_EPIC,
    DELETE_ALL_SUB,
    DELETE_SIMPLE_BY_ID,
    DELETE_EPIC_BY_ID,
    DELETE_SUB_BY_ID,
    WRONG_URI,
    WRONG_METHOD,
    UNKNOWN,

}
